version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: local_dev_db
      MYSQL_USER: localuser
      MYSQL_PASSWORD: localpassword
    volumes:
      - mysql_data:/var/lib/mysql

  mongo_test:
    image: mongo:latest
    container_name: mongo_test
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mysql_test:
    image: mysql:latest
    container_name: mysql_test
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: local_dev_test_db
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword

volumes:
  mongo_data:
  mysql_data:
